'use client';

import { useState, useRef, useEffect, KeyboardEvent } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FiSend, FiCpu } from 'react-icons/fi';
import { BsStars } from 'react-icons/bs';

interface Message {
  role: 'user' | 'assistant';
  content: string;
}

const SUGGESTED_PROMPTS = [
  "What projects has Imad built?",
  "What's his tech stack?",
  "Tell me about his trading bot",
  "Is Imad open to work?",
];

function parseMarkdown(text: string) {
  if (!text) return '';
  let html = text;

  // Remove redundant markdown underlines
  html = html.replace(/^=+$/gm, '');
  html = html.replace(/^-+$/gm, '');

  // Headers
  html = html.replace(/^### (.*$)/gim, '<h3 class="font-bold text-white text-[12px] tracking-wider mt-5 mb-1 uppercase opacity-70">$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2 class="font-bold text-white text-sm mt-5 mb-2">$1</h2>');
  html = html.replace(/^# (.*$)/gim, '<h1 class="font-bold text-white text-base mt-5 mb-2">$1</h1>');

  // Lists
  html = html.replace(/^[\*\-] (.*$)/gim, '<li class="ml-4 list-disc space-y-1">$1</li>');

  // Bold
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong class="text-white font-semibold">$1</strong>');
  
  // Newlines
  html = html.replace(/\n/g, '<br/>');
  
  // Cleanup excessive breaks generated by the raw markdown
  html = html.replace(/(<br\/>)+<h/g, '<h');
  html = html.replace(/<\/h[1-3]>(<br\/>)+/g, '</h3>');
  html = html.replace(/<\/li>(<br\/>)+<li/g, '</li><li');
  html = html.replace(/(<br\/>)+$/g, '');

  return html;
}

export default function ChatWindow() {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'assistant',
      content: "Hey! I'm Imad's AI — I know everything about him. Ask me anything: his projects, skills, background, or whether he's open to work. 🚀",
    },
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [showSuggestions, setShowSuggestions] = useState(true);
  const chatMessagesRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const abortRef = useRef<AbortController | null>(null);

  const scrollToBottom = () => {
    if (chatMessagesRef.current) {
      chatMessagesRef.current.scrollTo({
        top: chatMessagesRef.current.scrollHeight,
        behavior: 'smooth',
      });
    }
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const sendMessage = async (text: string) => {
    const trimmed = text.trim();
    if (!trimmed || isLoading) return;

    setShowSuggestions(false);
    const userMsg: Message = { role: 'user', content: trimmed };
    const updatedMessages = [...messages, userMsg];
    setMessages(updatedMessages);
    setInput('');
    setIsLoading(true);

    // Append a placeholder assistant message for streaming
    setMessages(prev => [...prev, { role: 'assistant', content: '' }]);

    abortRef.current = new AbortController();

    try {
      // Filter out the initial assistant greeting, Llama-3 models on Groq require the conversation to start with a user message.
      const apiMessages = updatedMessages.filter(
        (msg, idx) => !(idx === 0 && msg.role === 'assistant')
      );

      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: apiMessages,
        }),
        signal: abortRef.current.signal,
      });

      if (!response.ok || !response.body) throw new Error('API error');

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let accumulated = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        const chunk = decoder.decode(value, { stream: true });
        accumulated += chunk;

        setMessages(prev => {
          const next = [...prev];
          next[next.length - 1] = { role: 'assistant', content: accumulated };
          return next;
        });
      }
    } catch (err: unknown) {
      if (err instanceof Error && err.name !== 'AbortError') {
        setMessages(prev => {
          const next = [...prev];
          next[next.length - 1] = {
            role: 'assistant',
            content: "Sorry, I ran into an issue finding that information. Please try again later.",
          };
          return next;
        });
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage(input);
    }
  };

  return (
    <div className="chat-window">
      {/* Header */}
      <div className="chat-header">
        <div className="chat-header-icon">
          <BsStars size={16} />
        </div>
        <div>
          <h3 className="chat-header-title">Chat with Imad</h3>
          <p className="chat-header-sub">AI &middot; Knows everything about me</p>
        </div>
        <div className="status-badge ml-auto border-none !bg-transparent !p-0">
          <span className="pulse-dot"></span>
          LIVE
        </div>
      </div>

      {/* Messages */}
      <div className="chat-messages" data-lenis-prevent ref={chatMessagesRef}>
        <AnimatePresence initial={false}>
          {messages.map((msg, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3 }}
              className={`flex w-full ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
            >
              <div className={msg.role === 'user' ? 'chat-bubble-user' : 'chat-bubble-ai'}>
                {msg.role === 'assistant' ? (
                  <div dangerouslySetInnerHTML={{ __html: msg.content ? parseMarkdown(msg.content) : (isLoading && i === messages.length - 1 ? '' : '...') }} />
                ) : (
                  msg.content
                )}
              </div>
            </motion.div>
          ))}
          {isLoading && messages[messages.length - 1].content === '' && (
            <motion.div
              key="typing"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="flex justify-start w-full"
            >
              <div className="chat-typing-indicator chat-bubble-ai border-none !bg-transparent px-2 py-1 flex items-center gap-1.5">
                <FiCpu className="text-[var(--text-secondary)] mr-1" size={14} />
                <span></span>
                <span></span>
                <span></span>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Suggested Prompts */}
      {showSuggestions && (
        <div className="chat-suggestions">
          {SUGGESTED_PROMPTS.map((prompt) => (
            <button
              key={prompt}
              onClick={() => sendMessage(prompt)}
              className="chat-suggestion-chip"
            >
              {prompt}
            </button>
          ))}
        </div>
      )}

      {/* Input */}
      <div className="chat-input-row">
        <textarea
          ref={inputRef}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          disabled={isLoading}
          placeholder="Ask me anything..."
          className="chat-input"
          rows={1}
          data-lenis-prevent
        />
        <button
          onClick={() => sendMessage(input)}
          disabled={isLoading || !input.trim()}
          className="chat-send-btn"
          aria-label="Send message"
        >
          <FiSend size={16} />
        </button>
      </div>
    </div>
  );
}
